### ISSUE TITLE
Caroussel -bron

### ISSUE THREAD

**Issue by iBadr49** [KaanKalmi/the-startup-responsive-interactieve-website#10]
- Als je een aantrekkelijke scroll-animatie wilt maken, kun je _**Swiperjs**_ gebruiken. 

> <img width="450" alt="Scherm­afbeelding 2024-01-12 om 10 28 33" src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/112857932/2a6ef39e-d0bf-44ab-b8ab-cd9aa356a249">

**Comment by KrijnHoetmer** [comment]
Ik <3 die wontfix hiero!

@iBadr49 dit wil je met CSS doen, niet met JS: https://tympanus.net/codrops/2024/01/24/experimental-css-only-carousels-with-scroll-driven-animations/ :)

**Comment by iBadr49** [comment]
Mijn bron heb ik van Cyd gekregen 🫠😂

**Comment by KrijnHoetmer** [comment]
En nou heb je er nog eentje bij om een goede vergelijking te kunnen maken :)

**Comment by iBadr49** [comment]
🫡
