### ISSUE TITLE
Line -height

### ISSUE THREAD

**Issue by iBadr49** [KaanKalmi/the-startup-responsive-interactieve-website#12]
- Voor de line-height op mobiele apparaten kun je vaak een iets grotere waarde overwegen dan op desktop, aangezien schermen kleiner zijn en de tekst beter leesbaar moet zijn.  De bedoeling is om een line-height te kiezen tussen 1,4 en 1,6 keer de lettergrootte op mobiele apparaten.

> <img width="450" alt="Scherm­afbeelding 2024-01-12 om 10 39 05" src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/112857932/f4f6615c-3ad6-45dd-8395-90dccf824699">

**Comment by KaanKalmi** [comment]
[Fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/574f454de331e90a158780909910c979fe9304e3)
