### ISSUE TITLE
html structuur/Leuk Design 

### ISSUE THREAD

**Issue by Ronabundy1** [KaanKalmi/the-startup-responsive-interactieve-website#13]
Je html structuur is overzichtelijk en goed gestructueerd waardoor het makkelijk te begrijpen is. < Header> <Main> en <Section>zorgt voor een goed overzicht van je code. verder zie ik  dat je al een carrousel interactie werkend heb gekregen in je ontwerp heel tof

**Comment by KaanKalmi** [comment]
ty
