### ISSUE TITLE
zorg ervoor dat je tekst zichtbaar blijft tijdens het laden van weblettertype

### ISSUE THREAD

**Issue by Ronabundy1** [KaanKalmi/the-startup-responsive-interactieve-website#14]
Gebruik de css-functie font-display om ervoor te zorgen dat tekst zichtbaar is voor gebruikers terwijl weblettertypen worden geladen.
<img width="575" alt="Schermafbeelding 2024-01-15 113053 tip " src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/118179932/8e502649-ddc8-4e73-a272-c57211d61ba0">

**Comment by KaanKalmi** [comment]
[gefixt in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/bef3d2e96f3ef955b7c696b4410e7006664bfad7)
