### ISSUE TITLE
comment in html zichtbaar

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#15]
Je hebt een comment in je html gezet wat zichtbaar is op jouw website. Ik zou deze weghalen?

https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/blob/bef3d2e96f3ef955b7c696b4410e7006664bfad7/index.html#L54

**Comment by KaanKalmi** [comment]
mevrouw Oosbree, ik vind dit niet fijn hoe durft u dit als issue erin te schieten bij mij. Ik dacht dat we _vrienden_ waren!

**Comment by KaanKalmi** [comment]
[fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/39b33c55a0e1af4f1727ceaa3cf21dea74d04b51)
