### ISSUE TITLE
Haal de comments weg uit JavaScript

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#16]
Het kan best chaotisch overkomen als je er naar kijkt. Het zijn notities, maar maak er geen boekwerk van. Ik zou af en toe een wat langere comment toevoegen, ipv achter elke regel. 

[JavaScript code](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/blob/e540be112a25350d46717b1c6b6904f02f30afd6/scripts/main.js#L1)

**Comment by KaanKalmi** [comment]
De comments zijn handig voor mij zodat ik altijd terug kan gaan en lezen wat wat doet in details, dus nee.
