### ISSUE TITLE
Suggestie idee: Meer diepte en contrast

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#17]
Probeer iets meer diepte en contrast in jouw pagina te maken. Het is nu onder aan de pagina met alle tekst, best wel leeg en vlak. Leuk idee dat het icoontjes bevat, maar probeer iets uit met wat boxshadows en boxes en geef het iets meer kleur contrast. 

![afbeelding_2024-01-19_114548372](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144005439/5fa6116f-c282-4be5-aac5-b4113e0c44a9)

**Comment by KaanKalmi** [comment]
De content is verwijdert, zoals ik heb uitgelegd in de issue met IDEE 2. Daarom weer de label wont fix en closed issue
