### ISSUE TITLE
Kleur toegankelijkheid laag

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#18]
Er gaat een witte tekst over een oranje image heen, waardoor deze minder leesbaar wordt. Misschien kan je de tekst groter maker of een shadow eroverheen gooien. **Wellicht een box met blur.** 

![Schermafbeelding 2024-01-19 115110](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144005439/b1f6b673-9178-4f73-a199-fa19afe061b9)

Voorbeeld van jouw pagina:
![Schermafbeelding 2024-01-19 115218](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144005439/9fc0cba0-dc87-4167-9e07-83345e626120)

**Comment by KaanKalmi** [comment]
![image](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144000125/25fde029-8e4d-4edd-aaf0-47797aaf49ac)

Hij klopt wel! er is een transparante grijze laag erover dus t oranje is donker genoeg!
