### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Remy2072** [KaanKalmi/the-startup-responsive-interactieve-website#19]
Voor sommige img heb je best lange namen met spaties erin. Probeer overzichtelijke en korte namen te gebruiken zonder spaties.

**Comment by KaanKalmi** [comment]
[fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/d5ed283482651c840ad3c5f2e432775a67e28d37)
