### ISSUE TITLE
Consistent   

### ISSUE THREAD

**Issue by Remy2072** [KaanKalmi/the-startup-responsive-interactieve-website#20]
Probeer consistent te blijven in css met de waarde die je gebruikt. Ik zie nog best veel verschillende waardes 'px, em. en ch'

**Comment by KaanKalmi** [comment]
Dit maakt niet uit, er zijn geen vaste regels over consistency with CSS Units, Ik grebuik de waardes die zijn gegeven door AlphaTango voor de fonts, de breakpoints gebruik ik px omdat dat makkelijker is om te veranderen, de ch staat er alleen voor zodat ik geen lange zinnen krijg en em voor padding omdat die relatief is.

Dus daarom ga ik dit niet veranderen!
