### ISSUE TITLE
IDEE: 2 carrousels voor meer opvulling van leegte

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#21]
Het is een idee om 2 carrousels te gebruiken i.p.v 1 carrousel op de pagina. Zo kan je meer informatie kwijt en zorgt het ervoor dat het er minder leeg uitziet.

**Comment by KaanKalmi** [comment]
added it in the [this](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/5a01000ffe463e58d5d630f68d0c8c4ec6fff7d7) commit
