### ISSUE TITLE
IDEE: seperate features in een box design

### ISSUE THREAD

**Issue by smolgeorgie** [KaanKalmi/the-startup-responsive-interactieve-website#22]
Om meer diepte te creëren in jouw design, kan je wellicht je text zetten in ''feature boxes''.  
Dit is een voorbeeld:

![image](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144005439/1dc53654-1392-4dc2-aa41-e2ad47ecd288)

**Comment by KaanKalmi** [comment]
Ik heb de content verwijdert omdat dit overbodig bleek te zijn aangezien de informatie staat op de pagina waar ik naartoe moest linken, daarom ook de label wont fix en closed
