### ISSUE TITLE
Space in <img> text element is niet toegestaan!

### ISSUE THREAD

**Issue by Abeeryu** [KaanKalmi/the-startup-responsive-interactieve-website#23]
https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/blob/3784f959985c37cfac52fe870358faecff00a251/index.html#L33

Het is niet handig om een space te gebruiken tuseen de text.
Bron:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by KaanKalmi** [comment]
[fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/d5ed283482651c840ad3c5f2e432775a67e28d37)
