### ISSUE TITLE
Gebruik een ander names voor classes

### ISSUE THREAD

**Issue by Abeeryu** [KaanKalmi/the-startup-responsive-interactieve-website#24]
https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/blob/3784f959985c37cfac52fe870358faecff00a251/index.html#L14-L20

Ik heb gemerkt dat je slideup en slideup2 gebruikt voor classes names, je kan een andere naming convention gebruiken. Dit zorgt ervoor dat uw code leesbaar en onderhoudbaar blijft.

Bron:

https://dev.to/stakedesigner/best-practices-for-naming-classes-in-html-and-css-files-2kb5

**Comment by KaanKalmi** [comment]
[In deze commit is het gefixt](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/cb195e9f2937675549e882a0c33b472af845bbbd)
