### ISSUE TITLE
zorg voor duidelijke classnames

### ISSUE THREAD

**Issue by lisagjh** [KaanKalmi/the-startup-responsive-interactieve-website#3]
https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/blob/946462c1c56bed73e6d093329176aaf45186f19c/index.html#L17

Hier heb je de classname "pink" gebruikt, dat zegt niet zoveel over wat het is.

**Comment by KaanKalmi** [comment]
[In deze commit heb ik de issue verwerkt](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/2a6ea0d653c4529ea97cd2f87a37639f02f4085c)
