### ISSUE TITLE
Contrast 

### ISSUE THREAD

**Issue by iBadr49** [KaanKalmi/the-startup-responsive-interactieve-website#5]
- Je kunt Pika gebruiken om je contrast te controleren. Zoals je kunt zien, is het contrast momenteel niet optimaal. Op je pagina passen de 'Breath of Fire'-kleur en de 'Fresh Blue'-kleur niet goed bij de roze achtergrond.

> <img width="500" alt="Scherm­afbeelding 2024-01-12 om 10 05 00" src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/112857932/c9684a26-0dc3-4248-a3d5-cfdad9c84b62">

> <img width="500" alt="Scherm­afbeelding 2024-01-12 om 10 05 58" src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/112857932/7850ad35-751d-497a-828c-b576819de4ff">

**Comment by KaanKalmi** [comment]
[Fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/574f454de331e90a158780909910c979fe9304e3)
