### ISSUE TITLE
Kleinere font-size 

### ISSUE THREAD

**Issue by Remy2072** [KaanKalmi/the-startup-responsive-interactieve-website#7]
Op mobiel is het font te groot waardoor het heel veel ruimte in beslag neemt voor andere content.

**Comment by KaanKalmi** [comment]
over welke van de font-sizes gaat het?

![image](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/144000125/79be1b6b-49f3-4d14-b130-79dba1a1498a)

**Comment by KaanKalmi** [comment]
[fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/691d49e45487721737afa6c67e258d782f2f6d79)
