### ISSUE TITLE
contrast zwart blauw

### ISSUE THREAD

**Issue by lisagjh** [KaanKalmi/the-startup-responsive-interactieve-website#8]
Het contrast tussen dit zwart en blauw is erg laag. Kijk of je dit kan verhogen. 

<img width="670" alt="Scherm­afbeelding 2024-01-12 om 10 22 11" src="https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/assets/131701505/aa20b6dd-9937-4799-a9dc-423dd9f52338">

**Comment by KaanKalmi** [comment]
[Fixed in deze commit](https://github.com/KaanKalmi/the-startup-responsive-interactieve-website/commit/574f454de331e90a158780909910c979fe9304e3)
